<%
	AdRs_intSeq              = AdRs_GetRows(0, tmpFor)
	AdRs_intIndex            = AdRs_GetRows(1, tmpFor)
	AdRs_intThread           = AdRs_GetRows(2, tmpFor)
	AdRs_intDepth            = AdRs_GetRows(3, tmpFor)
	AdRs_strLoginID          = AdRs_GetRows(4, tmpFor)
	AdRs_intCategory         = AdRs_GetRows(5, tmpFor)
	AdRs_strName             = AdRs_GetRows(6, tmpFor)
	AdRs_strNickName         = AdRs_GetRows(7, tmpFor)
	AdRs_strPassword         = AdRs_GetRows(8, tmpFor)
	AdRs_strEmail            = AdRs_GetRows(9, tmpFor)
	AdRs_strHomepage         = AdRs_GetRows(10, tmpFor)
	AdRs_strSubject          = AdRs_GetRows(11, tmpFor)
	AdRs_strSubjectStyle     = SPLIT(AdRs_GetRows(12, tmpFor), ",")
	AdRs_strContent          = AdRs_GetRows(13, tmpFor)
	AdRs_strLink1            = AdRs_GetRows(14, tmpFor)
	AdRs_strLink2            = AdRs_GetRows(15, tmpFor)
	AdRs_strBoardBg          = AdRs_GetRows(16, tmpFor)

	IF AdRs_GetRows(17, tmpFor) <> "" AND ISNULL(AdRs_GetRows(17, tmpFor)) = False THEN
		AdRs_strIpAddr = REPLACE(AdRs_GetRows(17, tmpFor), MID(AdRs_GetRows(17, tmpFor), InStrRev(AdRs_GetRows(17, tmpFor), ".")), ".*")
	ELSE
		AdRs_strIpAddr = "none"
	END IF

	AdRs_bitDelete           = AdRs_GetRows(18, tmpFor)
	AdRs_bitHtml             = AdRs_GetRows(19, tmpFor)
	AdRs_bitHtmlBr           = AdRs_GetRows(20, tmpFor)
	AdRs_bitText             = AdRs_GetRows(21, tmpFor)
	AdRs_bitNotice           = AdRs_GetRows(22, tmpFor)
	AdRs_bitReMail           = AdRs_GetRows(23, tmpFor)
	AdRs_bitSecret           = AdRs_GetRows(24, tmpFor)
	AdRs_strSecretID         = AdRs_GetRows(25, tmpFor)
	AdRs_bitBad              = AdRs_GetRows(26, tmpFor)
	AdRs_intRead             = AdRs_GetRows(27, tmpFor)
	AdRs_intVote             = AdRs_GetRows(28, tmpFor)
	AdRs_intComment          = AdRs_GetRows(29, tmpFor)
	AdRs_intFileCount        = AdRs_GetRows(30, tmpFor)
	AdRs_intImgCount         = AdRs_GetRows(31, tmpFor)
	AdRs_strFileCode         = AdRs_GetRows(32, tmpFor)
	AdRs_dateCmtDate         = AdRs_GetRows(33, tmpFor)
	AdRs_dateRegDate         = AdRs_GetRows(34, tmpFor)
	AdRs_strMarkImage        = AdRs_GetRows(35, tmpFor)
	AdRs_strUserImage        = AdRs_GetRows(36, tmpFor)
	AdRs_strFileName         = AdRs_GetRows(37, tmpFor)
	AdRs_strFileImage        = AdRs_GetRows(38, tmpFor)
	AdRs_strCategory         = AdRs_GetRows(39, tmpFor)
	AdRs_strAddData1         = AdRs_GetRows(40, tmpFor)
	AdRs_strAddData2         = AdRs_GetRows(41, tmpFor)
	AdRs_strAddData3         = AdRs_GetRows(42, tmpFor)
	AdRs_strAddData4         = AdRs_GetRows(43, tmpFor)
	AdRs_strAddData5         = AdRs_GetRows(44, tmpFor)
	AdRs_strAddData6         = AdRs_GetRows(45, tmpFor)
	AdRs_strAddData7         = AdRs_GetRows(46, tmpFor)
	AdRs_strAddData8         = AdRs_GetRows(47, tmpFor)
	AdRs_strAddData9         = AdRs_GetRows(48, tmpFor)
	AdRs_strAddData10        = AdRs_GetRows(49, tmpFor)
%>