<%
	REDIM DIM_strBoardMsg(30)

	SELECT CASE CONF_strLanguage
	CASE "1"

	DIM_strBoardMsg(0)  = "등록자 이름을 입력해 주시기 바랍니다."
	DIM_strBoardMsg(1)  = "비밀번호를 입력해 주시기 바랍니다."
	DIM_strBoardMsg(2)  = "게시글 제목을 입력해 주시기 바랍니다."
	DIM_strBoardMsg(3)  = "첨부파일이 업로드금지 파일이거나 업로드 사이즈를 초과해서\n업로드가 되지 않은 파일이 있습니다."
	DIM_strBoardMsg(4)  = "게시글 등록이 완료되었습니다."
	DIM_strBoardMsg(5)  = "관리자가 승인 후 게시글이 게시됩니다."
	DIM_strBoardMsg(6)  = "게시글 삭제 권한이 없습니다."
	DIM_strBoardMsg(7)  = "비밀번호가 일치하지 않습니다."
	DIM_strBoardMsg(8)  = "게시글이 삭제되었습니다."
	DIM_strBoardMsg(9)  = "답변글이 존재하는 게시글은 삭제가 되지 않습니다."
	DIM_strBoardMsg(10) = "부적절한 게시글로 신고된 게시글 입니다."
	DIM_strBoardMsg(11) = "회원 로그인 되었습니다."
	DIM_strBoardMsg(12) = "로그아웃이 정상적으로 처리되었습니다."
	DIM_strBoardMsg(13) = "등록되어 있지 않은 회원아이디 입니다."
	DIM_strBoardMsg(14) = "비밀번호를 올바르게 입력해 주시기 바랍니다."
	DIM_strBoardMsg(15) = "로그인이 되어 있지 않습니다."
	DIM_strBoardMsg(16) = "현재글은 비밀게시글 입니다."
	DIM_strBoardMsg(17) = "게시글 비밀번호가 올바르지 않습니다."
	DIM_strBoardMsg(18) = "게시글을 열람할 권한이 없습니다."
	DIM_strBoardMsg(19) = "답변글을 등록할 수 없습니다."
	DIM_strBoardMsg(20) = "게시글 수정권한이 없습니다."
	DIM_strBoardMsg(21) = "[알림] 게시글이 등록되었습니다."
	DIM_strBoardMsg(22)  = "게시글 수정이 완료되었습니다."
	DIM_strBoardMsg(23)  = "승인되지 않은 회원아이디 입니다."
	DIM_strBoardMsg(24)  = "탈퇴처리된 회원 아이디 입니다."
	DIM_strBoardMsg(25)  = "삭제된 게시글 이거나 올바르게 접근하지 않으셨습니다."
	DIM_strBoardMsg(26)  = "관리자의 승인이 필요한 게시글 입니다."
	DIM_strBoardMsg(27)  = "댓글을 수정권한이 없습니다."

	CASE "2"

	DIM_strBoardMsg(0)  = "Please input your name or ID."
	DIM_strBoardMsg(1)  = "Please input your password."
	DIM_strBoardMsg(2)  = "Please title your article."
	DIM_strBoardMsg(3)  = "There may be a file or fiels that can not be uploaded due to banning of uploading attached files\n\nor exessive uploading size."
	DIM_strBoardMsg(4)  = "Your post has been registered successfuly."
	DIM_strBoardMsg(5)  = "Your posting will completed after administrator's confirmation."
	DIM_strBoardMsg(6)  = "You do not have permission to deleting."
	DIM_strBoardMsg(7)  = "Your password does not match."
	DIM_strBoardMsg(8)  = "Deletion of post(s) is completed."
	DIM_strBoardMsg(9)  = "It is impossible to delete article which has answer article belongs to it."
	DIM_strBoardMsg(10) = "Your postage has been reported in violation."
	DIM_strBoardMsg(11) = "You are logged in."
	DIM_strBoardMsg(12) = "You are logged out."
	DIM_strBoardMsg(13) = "Your member identification is not registered one."
	DIM_strBoardMsg(14) = "You must correctly type your password."
	DIM_strBoardMsg(15) = "Use after logging in."
	DIM_strBoardMsg(16) = "Curernt posting is in secret posting mode."
	DIM_strBoardMsg(17) = "You did not type correct password for the secret board."
	DIM_strBoardMsg(18) = "You have no authorization to read posts."
	DIM_strBoardMsg(19) = "You do not have permission to reply to posts."
	DIM_strBoardMsg(20) = "You have no authority to modify this article."
	DIM_strBoardMsg(21) = "Registered of post(s) is completed."
	DIM_strBoardMsg(22)  = "Your post has been edited successfuly."
	DIM_strBoardMsg(23)  = "This ID has not been approved."
	DIM_strBoardMsg(24)  = "It is an eliminated ID."
	DIM_strBoardMsg(25)  = "This post has been deleted."
	DIM_strBoardMsg(26)  = "This post needs to be approved by the administrator."
	DIM_strBoardMsg(27) = "You have no authority to modify this article."

	END SELECT
%>